#!/usr/bin/python3

# Library imports
import requests, sys,json,io

user_api_key = "API KEY HERE"
# Get hash as parameter
user_hash = str(sys.argv[1])

params = {
    'apikey': user_api_key,
    'resource': user_hash 
    }
  
# Make get call and store it on response variable
response = requests.get('https://www.virustotal.com/vtapi/v2/file/report', params=params)

# Turn the respose into json
json_response = response.json()

# Write report to file on the same directory as the script
with open('data.txt', 'w') as f:
  json.dump(json_response, f, ensure_ascii=False)
