#!/usr/bin/python3
import requests, sys,json

user_api_key = "API_KEY_HERE"
# Get hash as parameter for the script
user_hash = str(sys.argv[1])

params = {
    'apikey': user_api_key,
    'resource': user_hash 
    }


def pp_json(json_thing, sort=True, indents=4):
    if type(json_thing) is str:
        print(json.dumps(json.loads(json_thing), sort_keys=sort, indent=indents))
    else:
        print(json.dumps(json_thing, sort_keys=sort, indent=indents))
        return None

response = requests.get('https://www.virustotal.com/vtapi/v2/file/report', params=params)

# turn the respose into json
json_response = response.json()


pretty_json = pp_json(json_response)

print(pretty_json)
